version: '2.0'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 8000:3000
        volumes:
            - ./frontend/public/:/app/public/
            - ./frontend/src/:/app/src/
    db:
        image: postgres:11
        environment:
            POSTGRES_USER: user
            POSTGRES_DB: db
            POSTGRES_PASSWORD: password

